[project]
name="lydia-api-scripts"
version = "0.0.1"
description = "Scripts til bruk i lydia-api"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.3",
]

[tool.pytest.ini_options]
pythonpath="src" # spesifiserer en liste av mapper pytest ser etter python-moduler i
