name: "Build and deploy lydia-api"
on: [ push ]

env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"

jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/cache@v2"
        with:
          "path": "~/.gradle/caches"
          "key": "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}"
          "restore-keys": "${{ runner.os }}-gradle-"
      - uses: "actions/setup-java@v2"
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Compile, run tests and build"
        run: "./gradlew build"
      - name: "Login to GitHub Docker Registry"
        uses: "docker/login-action@v1"
        with:
          "registry": "ghcr.io"
          "username": "${{ github.actor }}"
          "password": "${{ secrets.GITHUB_TOKEN }}"
      - name: "Build and push the Docker image"
        uses: "docker/build-push-action@v2"
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,${{ env.IMAGE }}

  deployAppToDev:
    name: "Deploy app to dev"
    needs: "build"
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/kan-slette-saker-med-status-vurderes'
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "dev-gcp"
          "RESOURCE": ".nais/nais.yaml"
          "VARS": ".nais/dev.yaml"

  deployAppToProd:
    name: "Deploy app to prod"
    needs: "deployAppToDev"
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Deploy to PROD"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "prod-gcp"
          "RESOURCE": ".nais/nais.yaml"
          "VARS": ".nais/prod.yaml"

  deployTopicsToDev:
    name: "Deploy topics to dev"
    runs-on: "ubuntu-latest"
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/kan-slette-saker-med-status-vurderes'
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"
      - name: "Deploy topics to dev-gcp"
        uses: "nais/deploy/actions/deploy@master"
        env:
          APIKEY: "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          CLUSTER: "dev-gcp"
          RESOURCE: ".nais/topics/ia-sak-hendelse-topic.yaml,.nais/topics/ia-sak-topic.yaml"
          VARS: ".nais/dev.yaml"

  deployTopicsToProd:
    name: "Deploy topics to prod"
    runs-on: "ubuntu-latest"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"
      - name: "Deploy topics to prod-gcp"
        uses: "nais/deploy/actions/deploy@master"
        env:
          APIKEY: "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          CLUSTER: "prod-gcp"
          RESOURCE: ".nais/topics/ia-sak-hendelse-topic.yaml,.nais/topics/ia-sak-topic.yaml"
          VARS: ".nais/prod.yaml"
