name: "Build and deploy lydia-api"
on:
  push:
    branches:
      - "main"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  "kodesjekk":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scanning
        uses: sonarsource/sonarcloud-github-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  "build":
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/cache@v2"
        with:
          "path": "~/.gradle/caches"
          "key": "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}"
          "restore-keys": "${{ runner.os }}-gradle-"
      - uses: "actions/setup-java@v2"
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Compile, run tests and build"
        run: "./gradlew build"
      - name: "Login to GitHub Docker Registry"
        uses: "docker/login-action@v1"
        with:
          "registry": "ghcr.io"
          "username": "${{ github.actor }}"
          "password": "${{ secrets.GITHUB_TOKEN }}"
      - name: "Build and push the Docker image"
        uses: "docker/build-push-action@v2"
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,${{ env.IMAGE }}

  "deployAppToDev":
    name: "Deploy app to dev"
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "dev-gcp"
          "RESOURCE": ".nais/nais.yaml"
          "VARS": ".nais/dev.yaml"
  "deployAppToProd":
    name: "Deploy app to prod"
    needs: "deployAppToDev"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Deploy to PROD"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "prod-gcp"
          "RESOURCE": ".nais/nais.yaml"
          "VARS": ".nais/prod.yaml"
#  "deployAlertsToDev":
#    name: "Deploy alerts to dev"
#    needs: "build"
#    runs-on: "ubuntu-18.04"
#    steps:
#    - uses: "actions/checkout@v2"
#    - name: "Deploy alerts to DEV"
#      uses: "nais/deploy/actions/deploy@v1"
#      env:
#        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#        "CLUSTER": "dev-gcp"
#        "RESOURCE": ".nais/alerts-dev.yaml"
#        "VARS": ".nais/dev.yaml"
#  "deployAlertsToProd":
#    name: "Deploy alerts to prod"
#    needs: "build"
#    runs-on: "ubuntu-18.04"
#    steps:
#    - uses: "actions/checkout@v2"
#    - name: "Deploy alerts to PROD"
#      uses: "nais/deploy/actions/deploy@v1"
#      env:
#        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#        "CLUSTER": "prod-gcp"
#        "RESOURCE": ".nais/alerts-prod.yaml"
#        "VARS": ".nais/prod.yaml"